#release configuration
#Tue Mar 11 14:02:02 GMT+04:00 2025
completedPhase=check-poms
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.scm.am.demo\:sfg-pet-data.empty=true
project.scm.am.demo\:sfg-pet-repo.connection=
project.scm.am.demo\:sfg-pet-repo.developerConnection=scm\:git\:git@github.com\:kzakaryan/sfg-pet-repo.git
project.scm.am.demo\:sfg-pet-repo.tag=HEAD
project.scm.am.demo\:sfg-pet-repo.url=
project.scm.am.demo\:sfg-pet-web.empty=true
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:git@github.com\:kzakaryan/sfg-pet-repo.git
